name: covid-npi
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.9
  - matplotlib==3.2.1
  - numpy==1.18.1
  - pandas==1.0.3
  - pip==19.3
  - xlrd==1.1.0
  - pip:
      - typer==0.3.2
      - -e .