[mongo]
url = "mongodb://zappa.uca.es:27038/"
username = ""
password = ""
database = ""
chunks = 10
date_min = "21-06-2020"

[npi]
fillna_date_end = "today"  # "today" or "start"

[cases]
movavg = 7
link = "https://cnecovid.isciii.es/covid19/resources/cases_tecnica_provincia.csv"