[mongo]
url = "mongodb://zappa.uca.es:27038/"
username = ""
password = ""
database = ""
chunks = 10
date_min = "21-06-2020"
statistics = ["Mean", "Median", "Standard deviation", "Interquantile range", "Coefficient of variation"]

[mongo.boxplot]
min = "#FFFFFF"
low_whisker = "#6BB9EE"
q25 = "#FFC0CB"
median = "#8B008B"
q75 = "#8B008B"
up_whisker = "#FFC0CB"
max = "#6BB9EE"

[npi]
fillna_date_end = "today"  # "today" or "start"

[cases]
movavg = 7
link = "https://cnecovid.isciii.es/covid19/resources/cases_tecnica_provincia.csv"