[postal_to_code]
1 = "VI"
2 = "AB"
3 = "A"
4 = "AL"
5 = "AV"
6 = "BA"
7 = "PM"
8 = "B"
9 = "BU"
10 = "CC"
11 = "CA"
12 = "CS"
13 = "CR"
14 = "CO"
15 = "C"
16 = "CU"
17 = "GI"
18 = "GR"
19 = "GU"
20 = "SS"
21 = "H"
22 = "HU"
23 = "J"
24 = "LE"
25 = "L"
26 = "LO"
27 = "LU"
28 = "M"
29 = "MA"
30 = "MU"
31 = "NA"
32 = "OR"
33 = "O"
34 = "P"
35 = "GC"
36 = "PO"
37 = "SA"
38 = "TF"
39 = "S"
40 = "SG"
41 = "SE"
42 = "SO"
43 = "T"
44 = "TE"
45 = "TO"
46 = "V"
47 = "VA"
48 = "BI"
49 = "ZA"
50 = "Z"
51 = "CE"
52 = "ML"


[code_to_provincia]
VI = "Álava"
AB = "Albacete"
A = "Alacant"
AL = "Almería"
AV = "Ávila"
BA = "Badajoz"
PM = "Illes Balears"
B = "Barcelona"
BU = "Burgos"
CC = "Cáceres"
CA = "Cádiz"
CS = "Castelló"
CR = "Ciudad Real"
CO = "Córdoba"
C = "A Coruña"
CU = "Cuenca"
GI = "Girona"
GR = "Granada"
GU = "Guadalajara"
SS = "Gipuzkoa"
H = "Huelva"
HU = "Huesca"
J = "Jaén"
LE = "León"
L = "Lleida"
LO = "La Rioja"
LU = "Lugo"
M = "Madrid"
MA = "Málaga"
MU = "Murcia"
NA = "Nafarroa"
OR = "Ourense"
O = "Asturias"
P = "Palencia"
GC = "Las Palmas"
PO = "Pontevedra"
SA = "Salamanca"
TF = "Sta. Cruz de Tenerife"
S = "Cantabria"
SG = "Segovia"
SE = "Sevilla"
SO = "Soria"
T = "Tarragona"
TE = "Teruel"
TO = "Toledo"
V = "Valéncia"
VA = "Valladolid"
BI = "Bizkaia"
ZA = "Zamora"
Z = "Zaragoza"
CE = "Ceuta"
ML = "Melilla"


[code_to_poblacion]
AB = 388270
A = 1879888
AL = 727945
VI = 333940
O = 1018784
AV = 157664
BA = 672137
PM = 1171543
B = 5743402
BI = 1159443
BU = 357650
CC = 391850
CA = 1244049
S = 582905
CS = 585590
CR = 495045
CO = 781451
C = 1121815
CU = 196139
SS = 727121
GI = 781788
GR = 919168
GU = 261995
H = 524278
HU = 222687
J = 631381
LE = 456439
L = 438517
LU = 327946
M = 6779888
MA = 1685920
MU = 1511251
NA = 661197
OR = 306650
P = 160321
GC = 1131065
PO = 945408
LO = 319914
SA = 329245
TF = 1044887
SG = 153478
SE = 1950219
SO = 88884
T = 816772
TE = 134176
TO = 703772
V = 2591875
VA = 520649
ZA = 170588
Z = 972528
CE = 84202
ML = 87076